=== mino98/stix/StixAgent/xml/workflow/npmn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.wimo.inf.ed.ac.uk/stix" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:stix="http://www.wimo.inf.ed.ac.uk/stix">
    <annotation>
    	<documentation>XML Schema for Stix Workflows</documentation></annotation>
    <element name="Workflow" type="stix:WorkflowComplexType"></element>
    <complexType name="MetadataComplexType">
    	<sequence>
    		<element name="Name" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<maxLength value="256"></maxLength>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="Author" minOccurs="0" maxOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<maxLength value="256"></maxLength>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="UUID" minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<pattern
    						value="[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}">
    					</pattern>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="Rev" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="0"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="Notes" type="string" minOccurs="0" maxOccurs="1"></element>
    		<element name="Enabled" type="boolean" maxOccurs="1" minOccurs="0" default="true"></element>
    		<element name="Validity" maxOccurs="1" minOccurs="0">
    			<complexType>
    				<sequence>
    					<element name="NotBefore" type="dateTime" minOccurs="0" maxOccurs="1"></element>
    					<element name="NotAfter" type="dateTime" maxOccurs="1" minOccurs="0"></element>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>
    <complexType name="AttributeSetComplexType">
    	<sequence>
    		<element minOccurs="0" maxOccurs="unbounded"
    			name="Attribute">
    			<complexType>
    				<sequence>
    					<element minOccurs="0" maxOccurs="1" name="Type"
    						type="string">
    					</element>
    					<element minOccurs="1" maxOccurs="1" name="Name"
    						type="string">
    					</element>
    					<element minOccurs="0" maxOccurs="1"
    						name="Value" type="string">
    					</element>
    				</sequence>
    				<attribute name="Persistent" type="boolean" use="optional" default="false"></attribute>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>
    <complexType name="WorkflowComplexType">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element minOccurs="1" maxOccurs="1" name="Metadata"
    			type="stix:MetadataComplexType">
    		</element>
    		<element minOccurs="0" maxOccurs="1" name="AttributeSet"
    			type="stix:AttributeSetComplexType">
    		</element>
    		<element name="Pool" type="stix:PoolComplexType"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>
    <complexType name="PoolComplexType">
        <sequence>
        	<element name="MessageCatch" type="stix:MessageCatchingEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="MessageThrow" type="stix:MessageThrowingEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="StartMessageEvent" type="stix:StartMessageEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="StartConditionEvent" type="stix:StartConditionEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="StartTimerEvent" type="stix:StartTimerEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="Task" type="stix:TaskComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="Timer" type="stix:TimerEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="Log" type="stix:LogEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="EndPlainEvent" type="stix:EndPlainEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="TerminateEvent" type="stix:TerminateEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        	<element name="ExclusiveGateway" type="stix:ExclusiveGatewayEventComplexType" minOccurs="0" maxOccurs="unbounded">
        	</element>
        </sequence>
        
        
        <attribute use="optional" name="Query" type="string"></attribute>
    	<attribute use="optional" name="x" type="int">
    	</attribute>
    	<attribute use="optional" name="y" type="int">
    	</attribute>
    </complexType>

    <complexType name="TaskComplexType">
    	<complexContent>
    		<extension base="stix:EventComplexType">
    			<sequence>
    				<element name="FlowMapping" maxOccurs="1"
    					minOccurs="1" type="stix:FlowMappingTaskComplexType">
    				</element>
    				<element name="DataMapping" maxOccurs="1"
    					minOccurs="0" type="stix:DataMappingComplexType">
    				</element>
    			</sequence>


    			<attribute name="Clazz" type="string" use="required"></attribute>


    			<attribute name="URL" type="string" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ParameterComplexType">
    	<sequence>
    		<element name="Name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<choice minOccurs="1">
    			<element name="Value" type="string" minOccurs="1"></element>
    			<element name="Attribute" type="string" minOccurs="1"></element>
    		</choice>
    	</sequence>
    </complexType>

    <complexType name="ExclusiveGatewayEventComplexType">
    	<complexContent>
    		<extension base="stix:EventComplexType">
                <choice>
    				<element name="FlowMapping" maxOccurs="1" minOccurs="1" type="stix:FlowMappingConditionComplexType">
    				</element>
    			</choice>


    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="StartEventComplexType">
    	<complexContent>
    		<extension base="stix:FlowEventComplexType"></extension>
    	</complexContent>
    </complexType>


    <complexType name="EventComplexType">
    	<attribute name="id" type="ID" use="required"></attribute>
    	<attribute name="x" type="int"></attribute>
    	<attribute name="y" type="int"></attribute>
    </complexType>

    <complexType name="EndPlainEventComplexType">
    	<complexContent>
    		<extension base="stix:EndEventComplexType"></extension>
    	</complexContent>
    </complexType>

    <complexType name="TerminateEventComplexType">
    	<complexContent>
    		<extension base="stix:EndEventComplexType"></extension>
    	</complexContent>
    </complexType>

    <complexType name="TimerEventComplexType">
    	<complexContent>
    		<extension base="stix:FlowEventComplexType">
    			<attribute name="duration" type="int"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="StartTimerEventComplexType">
    	<complexContent>
    		<extension base="stix:StartEventComplexType">
    			<attribute name="timer" type="dateTime"
    				use="required">
    			</attribute>
    			<attribute name="period" type="long" use="optional" default="-1"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="StartConditionEventComplexType">
    	<complexContent>
    		<extension base="stix:StartEventComplexType">
    			<attribute name="condition" type="string" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="StartMessageEventComplexType">
    	<complexContent>
    		<extension base="stix:StartEventComplexType">
    			<attribute name="message" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="MessageThrowingEventComplexType">
    	<complexContent>
    		<extension base="stix:FlowEventComplexType">
    			<sequence>
    				<element name="DataMapping"
    					type="stix:DataMappingComplexType" minOccurs="1"
    					maxOccurs="1">
    				</element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    <complexType name="DataMappingComplexType">
    	<sequence>
    		<element minOccurs="0" maxOccurs="1" name="in" type="stix:DataInComplexType">
    		</element>
    		<element minOccurs="0" maxOccurs="1" name="out" type="stix:DataOutComplexType">
    		</element>
    	</sequence>
    </complexType>
    <complexType name="DataInComplexType">
    	<sequence>
    		<element minOccurs="0" maxOccurs="unbounded"
    			name="parameter" type="stix:ParameterComplexType">
    		</element>
    	</sequence>
    </complexType>
    <complexType name="DataOutComplexType">
    	<sequence>
    		<element minOccurs="0" maxOccurs="unbounded"
    			name="parameter" type="stix:ParameterComplexType">
    		</element>
    	</sequence>
    </complexType>
    <complexType name="FlowMappingComplexType">
    	<sequence>
    		<element name="out" type="IDREF"></element>
    	</sequence>
    </complexType>
    <complexType name="FlowMappingConditionComplexType">

        <sequence>
    		<element name="out" type="stix:FlowOutConditionComplexType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="MessageCatchingEventComplexType">
    	<complexContent>
    		<extension base="stix:FlowEventComplexType">
    			<sequence>
    				<element name="DataMapping"
    					type="stix:DataMappingComplexType" minOccurs="1"
    					maxOccurs="1">
    				</element>
    			</sequence>
    			<attribute name="timeout" type="long" use="optional" default="-1"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="LogEventComplexType">
    	<complexContent>
    		<extension base="stix:FlowEventComplexType">
    			<sequence>
    				<element name="DataMapping"
    					type="stix:DataMappingComplexType" minOccurs="1"
    					maxOccurs="1">
    				</element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="FlowMappingTaskComplexType">
    	<complexContent>
    		<extension base="stix:FlowMappingComplexType">
    			<choice>
    				<element name="error" type="IDREF"></element>
    				<element name="timeout">
    					<complexType>
    						<simpleContent>
    							<extension base="IDREF">
    								<attribute name="duration"
    									type="int">
    								</attribute>
    							</extension>
    						</simpleContent>
    					</complexType></element>
    			</choice>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="EndEventComplexType">
    	<complexContent>
    		<extension base="stix:EventComplexType"></extension>
    	</complexContent>
    </complexType>

    <complexType name="FlowEventComplexType">
    	<complexContent>
    		<extension base="stix:EventComplexType">
    			<sequence>
    				<element name="FlowMapping" type="stix:FlowMappingComplexType" minOccurs="1"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="FlowOutConditionComplexType">
    	<simpleContent>
    		<extension base="IDREF">
    			<attribute name="condition" type="string"
    				use="optional">
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>

</schema>

=== mino98/stix/StixAgent/xml/test/evaluationworkflow.xml
<?xml version="1.0"?>
<Workflow xmlns="http://www.wimo.inf.ed.ac.uk/stix" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.wimo.inf.ed.ac.uk/stix ../workflow/npmn.xsd ">

	<Metadata>
		<Name>Comprehensive Workflow</Name>
		<Author>Stix team</Author>
		<UUID>12345678-e29b-41d4-a716-446655440000</UUID>
		<Rev>1</Rev>
		<Notes>An example workflow with all events and tasks</Notes>
		<Enabled>true</Enabled>
		<Validity>
			<NotBefore>2009-01-01T09:00:00</NotBefore>
			<NotAfter>2010-12-31T09:00:00</NotAfter>
		</Validity>
	</Metadata>
	<AttributeSet>
		<Attribute>
			<Type>int</Type>
			<Name>evalAttribute</Name>
		</Attribute></AttributeSet>

	<Pool Query="ON location == SiteB DO" x="100" y="300">
		<MessageCatch id="stix-104">
			<FlowMapping>
				<out>stix-105</out>
			</FlowMapping>
			<DataMapping>
				<in>
					<parameter>
						<Name>messageName</Name>
						<Value>evalMsg</Value>
					</parameter></in>
				<out>
					<parameter>
						<Name>messageContent</Name>
						<Attribute>evalAttribute</Attribute>
						
					</parameter></out></DataMapping>
		</MessageCatch><MessageThrow id="stix-103">
			<FlowMapping>
				<out>stix-104</out>
			</FlowMapping>
			<DataMapping>
				<in>
					<parameter>
						<Name>messageName</Name>
						<Value>evalMsg</Value>
					</parameter>
					<parameter>
						<Name>messageContent</Name>
						<Value>12</Value>
					</parameter>
					<parameter>
						<Name>destination</Name>
						<Value>192.168.2.104</Value>
					</parameter></in></DataMapping>
</MessageThrow><StartTimerEvent id="stix-101" timer="2010-02-08T17:00:00"
			period="300000">
			<FlowMapping>
				<out>stix-102</out>
			</FlowMapping>
		</StartTimerEvent>

		<Task Clazz="uk.ac.ed.inf.wimo.stix.agent.task.GetSNR"
		URL="http://www.wimo.inf.ed.ac.uk/stix/GetSNR.class" 
		id="stix-102" x="100" y="300">
			<FlowMapping>
				<out>stix-103</out>
				<timeout>stix-103</timeout>
			</FlowMapping>
		</Task><Task URL="http://www.wimo.inf.ed.ac.uk/stix/Reboot.class" Clazz="uk.ac.ed.inf.wimo.stix.agent.task.Reboot" id="stix-106">
			<FlowMapping>
				<out>stix-108</out>
				<error>stix-108</error>
			</FlowMapping>
		</Task><Timer id="stix-108" duration="5000">
			<FlowMapping>
				<out>stix-104</out>
			</FlowMapping>
		</Timer>
	
		
		<Log id="stix-107">
			<FlowMapping>
				<out>stix-109</out>
			</FlowMapping>
			<DataMapping>
				<in>
					<parameter>
						<Name>message</Name>
						<Value>SNR OK!</Value>
					</parameter></in></DataMapping>
		</Log><EndPlainEvent id="stix-109" x="123" y="345"></EndPlainEvent><ExclusiveGateway id="stix-105">
			<FlowMapping>
				<out condition="evalAttribute == 10">stix-106</out>
				<out>stix-107</out>
			</FlowMapping>
</ExclusiveGateway>
		
		
		
		
	</Pool>
</Workflow>
